<a href="https://colab.research.google.com/github/ruedasnayeli17/unidad1/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy es una libreria de Python.
Numpy se utiliza para trabajar con
matrices o arreglos.
Numpy es la breviatura de "python numerico"
tambien tiene funciones para trabajar en el
dominio de algebra lineal, la transformada
y las matrices
En python tenemos listas que sirven como
matrices. pero como objetivo proporcionar un
objeto de matriz que sea 50 veces mas
rapido que las listas tradicionales.

In [6]:
#primero tenemos que importar la libreria
import numpy

arreglo = numpy.array([1,2,3,4,5])
print(arreglo)

[1 2 3 4 5]


Numpy como np
Numpy generalmente se importa bajo el alias np
En python los alias son un nombre alternativo para referirse a la misma cosa

In [5]:
import numpy as np

arreglo=np.array([6,7,8,9,10])
print(arreglo)

[ 6  7  8  9 10]


comprobando la version de numpy la cadena
de la region se almacena en el atributo
__version__


In [4]:
import numpy as np

print(np.__version__)


2.0.2


Numpy creando matrices
crear un objeto ndarray de numpy
Numpy se utiliza para trabajar con matrices
el objeto de matriz de llama ndarray
podemos crear un numpy ndarray utilizando la funcion
array()  

In [11]:
import numpy as numpy
arreglo = np.array(["raul","ana","kimberly","yazmin"])
print(arreglo)
print(type(arreglo))

['raul' 'ana' 'kimberly' 'yazmin']
<class 'numpy.ndarray'>


Dimensiones en matrices
Una dimension en matrices es un nivel de profundidad
de matriz (matrices anidadas)
Una matriz unidada contiene matrices
como elementos
Matrices 0-D son elementos de una matriz,
cada valor de una matriz es una matriz 0-D.
Ejemplo crea una matriz 0-D con un valor de 42

In [15]:
import numpy as np

arreglo= np.array(42)

print(arreglo)


42


matrices 1-D
una matriz que tiene matrices 0-D
como elementos se denomina matriz
unidimensional o 3-D
Estas son las matrices mas comunes
y basicas
Ejemplo: crea una matriz de 1-0 que tenga los valores
1,2,3,4,5

In [17]:
import numpy as np

arreglo=np.array([1,2,3,4,5])

print(arreglo)


[1 2 3 4 5]


matrices 2-D
una matriz que tiene matrices de 1-D
como elementos se denomina matriz 2-D
a menudo se utilizan para representar matrices de segundo orden, NumPy
tiene un submodulo completo dedicado a operaciones con matrices llamado
numpy.mat
Ejemplo:crea una matriz 2D que contenga dos matrices con los
valores 123 y 456

In [22]:
import numpy as np

arreglo= np.array([[1,2,3],[4,5,6]])

print(arreglo)

[[1 2 3]
 [4 5 6]]


Matrices 3D
una matriz que tiene 2D se
denomina matriz 3D
estas matrices se utilizan para
representar una matriz de tercer orden
Ejemplo: crea una matriz 3D con dos matrices
bidimensionales, ambas conteniendo dos
matrices con los valores 123 y 456

In [25]:
import numpy as np
arreglo=np.array([[[1,2,3,],[4,5,6]],[[1,2,3],[4,5,6]]])

print(arreglo)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
